CREATE TABLE IF NOT EXISTS users(
    username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  createdAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)